// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class HelloGoogleTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void helloGoogle() {
        driver.get("https://www.google.com/");
        driver.manage().window().setSize(new Dimension(1853, 941));
        driver.findElement(By.name("q")).click();
        driver.findElement(By.name("q")).sendKeys("El juego de En");
        driver.findElement(By.cssSelector(".sbhl b")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".jNVrwc .LC20lb"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        js.executeScript("window.scrollTo(0,265)");
        driver.findElement(By.name("q")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".RzdJxc:nth-child(1) .hMJ0yc:nth-child(2)"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.name("q")).click();
        driver.findElement(By.name("q")).sendKeys("el juego de ender full");
        driver.findElement(By.cssSelector(".sbhl b")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".RzdJxc:nth-child(1) .WZIVy"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".RzdJxc:nth-child(3) .fc9yUc:nth-child(1)"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.close();
    }
}
